/**
 * Explicação prática de cada critério dos guias de compra (um texto por critério, na mesma ordem de `criterios`
 * em guias.ts). Serve ao carrossel "Antes de comprar" e à seção "O que observar antes de comprar" dos guias.
 *
 * Regras para escrever aqui: orientação geral e que envelhece devagar; nada sobre um produto ou marca específica;
 * nada que pareça teste ou opinião própria; saúde só com aviso de cautela; números só como referência ("cerca de",
 * "em geral"), e só quando são amplamente aceitos.
 */
export const EXPLICACOES_DOS_CRITERIOS: Record<string, string[]> = {
  'fones-bluetooth': [
    'Veja as horas de uso só no fone e quantas cargas o estojo dá. Bateria curta vira dor de cabeça no dia a dia.',
    'Fone desconfortável acaba na gaveta. Prefira modelos que vêm com borrachinhas de tamanhos diferentes.',
    'A descrição quase nunca mostra a qualidade do microfone. Procure comentários de quem usa em ligações e reuniões.',
    'IPX4 aguenta suor e respingos; IPX7 aguenta imersão rápida em água. Para treino, não escolha sem esse código.',
    'Bluetooth 5 ou mais novo costuma ter conexão mais estável. Confira se o seu celular é compatível.',
  ],
  smartwatches: [
    'O fabricante mede em condições ideais. Com GPS e notificações ligados, costuma durar bem menos: veja relatos de uso.',
    'Alguns relógios funcionam melhor, ou só funcionam, com um dos sistemas. Confira antes de comprar.',
    'Sem GPS próprio, o relógio depende do celular para registrar corrida. Os sensores de saúde ajudam, mas não substituem avaliação médica.',
    'Procure 5 ATM ou IP68. "Resistente a respingos" não serve para nadar.',
    'Tela AMOLED costuma ter cores melhores. Pulso fino pede caixa menor: veja o diâmetro em milímetros.',
  ],
  celulares: [
    'O armazenamento é o que enche: fotos, vídeos e apps. 128 GB atende uso básico; quem grava muito vídeo deve olhar 256 GB ou mais.',
    'A capacidade em mAh importa, mas o consumo da tela e do processador também. Carregador rápido faz diferença na rotina.',
    'Mais megapixels não garantem foto melhor à noite. Procure fotos de teste feitas em ambiente escuro.',
    'Sem atualizações de segurança o aparelho fica vulnerável mais cedo. Muitas marcas informam o prazo no site.',
    'Muitos modelos vêm sem carregador. Some o preço de um carregador original ao comparar ofertas.',
  ],
  notebooks: [
    'Para estudar e trabalhar com navegador, 8 GB de RAM é o mínimo confortável; 16 GB se você abre muitas abas ou programas pesados.',
    'O SSD faz o notebook ligar e abrir programas muito mais rápido que o HD. Hoje, quase todo notebook bom já vem com SSD.',
    'Full HD (1920x1080) é um bom ponto de partida. Telas IPS costumam ter ângulos de visão e cores melhores.',
    'O fabricante mede em condições ideais; na prática, a duração costuma ser menor. Procure relatos de uso real.',
    'Em geral, abaixo de 1,5 kg é fácil de levar na mochila todo dia; acima de 2 kg já cansa.',
  ],
  'smart-tvs': [
    'Como referência, sente a uma distância de 1,5 a 2,5 vezes a diagonal da TV. Numa sala de 3 metros, de 50 a 55 polegadas costuma servir bem.',
    'Em telas menores, a diferença do Full HD para o 4K é difícil de notar. A partir de 43 polegadas, o 4K compensa.',
    'Confira se o sistema tem os apps que você usa (Netflix, YouTube, Globoplay) e se ainda recebe atualizações.',
    '60 Hz atende a maioria. Para videogame novo, procure 120 Hz e entrada HDMI 2.1.',
    'Conte os seus aparelhos: videogame, soundbar, decodificador. Poucas entradas obrigam a ficar trocando cabo.',
  ],
  monitores: [
    '24 polegadas combina com Full HD. A partir de 27, vale pensar em QHD para a imagem não ficar granulada.',
    '60 Hz serve para trabalho e filmes. Em jogos rápidos, 144 Hz deixa o movimento visivelmente mais suave.',
    'IPS tem cores e ângulos melhores, bom para trabalho e edição. VA tem mais contraste, bom para filmes.',
    'Confira se as entradas combinam com o seu computador. Para alta taxa de atualização, o DisplayPort costuma ser a melhor opção.',
    'Tela na altura dos olhos evita dor no pescoço. Sem ajuste de altura, pode ser preciso comprar um suporte.',
  ],
  ssds: [
    'Deixe folga: SSD quase cheio perde desempenho. Para o sistema e os programas, 500 GB é um bom começo; guarda muitos jogos? Pense em 1 TB.',
    'NVMe é bem mais rápido, mas só funciona se o computador tiver o encaixe M.2 compatível. Confira o manual da placa-mãe.',
    'Números maiores ajudam a copiar arquivos grandes. No uso comum do dia a dia, a diferença entre bons SSDs é pequena.',
    'Garantia longa (3 a 5 anos) indica confiança do fabricante. Guarde a nota fiscal.',
  ],
  'caixas-de-som-bluetooth': [
    'Desconfie de potência em "PMPO", que costuma ser inflada. O tamanho da caixa pesa mais no grave do que o número de watts.',
    'Veja as horas em volume médio, não no máximo. Em volume alto, a bateria acaba bem antes do informado.',
    'IPX5 aguenta respingos e chuva; para piscina ou praia, procure IPX7.',
    'Caixa grande soa melhor, mas pesa na mochila. Escolha pelo uso: casa ou viagem.',
    'Algumas permitem ligar duas caixas iguais para som estéreo ou mais volume. Vale se você quer ampliar depois.',
  ],
  'air-fryers': [
    'Até 4 L atende 1 ou 2 pessoas; para a família, 5 L ou mais. Caixa grande ocupa espaço na bancada.',
    'Potência maior aquece mais rápido. Controle de temperatura e timer dão mais precisão do que botões simples.',
    'Cesta antiaderente e que vai na lava-louças economiza tempo. Confira se pode lavar com água.',
    'Úteis se você assa ou desidrata alimentos. Se só vai fritar, não pague a mais por funções que não vai usar.',
    'Alguns modelos fazem barulho de ventilador alto. Veja comentários de quem usa em apartamento.',
  ],
  'aspiradores-robo': [
    'Em casa grande, veja se ele volta sozinho à base e retoma a limpeza depois de recarregar.',
    'Alguns têm reservatório de água, mas o pano costuma ser básico. Para piso muito sujo, nada substitui o pano manual.',
    'Modelos com mapa (laser ou câmera) limpam em linhas, sem esbarrar em tudo. Sem mapeamento, o trajeto é aleatório e mais lento.',
    'É medida em Pa. Quanto maior, melhor para tapete e pelos de pet; em piso liso, a diferença é pequena.',
    'Reservatório pequeno enche rápido, principalmente com pet em casa. Veja se é fácil de tirar e limpar.',
  ],
  'aspiradores-de-po': [
    'Aparece em watts ou kPa, conforme o modelo. Para tapete e pelos de pet, quanto mais, melhor.',
    'Sem fio é prático, mas a bateria costuma durar menos de uma hora. Para casa grande, o com fio rende mais.',
    'Reservatório pequeno obriga a esvaziar várias vezes. Saco descartável é mais higiênico, mas gera custo.',
    'Aspirador forte costuma ser barulhento. Veja os decibéis informados e relatos de uso.',
    'Bocal para cantos e escova para sofá aumentam a utilidade. Confira o que vem na caixa.',
  ],
  cafeteiras: [
    'Filtro rende mais xícaras e é barata. Expresso e cápsulas dão café mais encorpado, mas custam mais por xícara.',
    'Faça a conta: cápsulas costumam custar várias vezes mais por xícara do que o café em pó.',
    'Defina quantas xícaras você faz de uma vez. Jarra grande desperdiça café se você toma pouco.',
    'Muitas peças pequenas dão trabalho. Veja se as peças podem ir na lava-louças.',
    'Jarra térmica mantém quente sem queimar o café, diferente da chapa que fica ligada.',
  ],
  liquidificadores: [
    'Potência maior tritura melhor gelo e frutas duras. A função "pulsar" já dá bastante controle, mesmo sem muitas velocidades.',
    'Vidro não mancha nem pega cheiro, mas é pesado e quebra. Plástico resistente é leve; inox é durável e custa mais.',
    '2 litros atende uma família. Para 1 ou 2 pessoas, 1 litro ou menos resolve e ocupa menos espaço.',
    'Procure a função para gelo ou lâminas reforçadas. Gelo em excesso pode forçar o motor.',
    'Lâminas removíveis facilitam a limpeza. Cuidado ao lavar para não se cortar.',
  ],
  ventiladores: [
    'Hélice maior move mais ar com menos barulho. Para sala ou quarto grande, prefira modelos maiores.',
    'Veja se o fabricante informa os decibéis. Para o quarto, prefira modelos silenciosos e com velocidade baixa.',
    'O timer desliga sozinho, bom para dormir. O controle remoto evita levantar toda hora.',
    'A oscilação distribui o ar pelo ambiente. Altura ajustável ajuda a direcionar o vento.',
    'Ventilador consome pouco, mas varia com a potência. Compare os watts se for deixar ligado por muitas horas.',
  ],
  geladeiras: [
    'Como referência, 250 a 350 L atende de 2 a 3 pessoas; famílias maiores costumam precisar de mais.',
    'Quanto melhor a classificação, menor o consumo. Como a geladeira fica ligada o tempo todo, a economia na conta de luz se paga.',
    'Frost free não forma gelo e dispensa degelo, mas custa mais. Degelo manual é mais barata e dá mais trabalho.',
    'Meça largura, altura e profundidade e deixe folga nas laterais, para ventilar e abrir a porta.',
    'Ligar na tensão errada pode queimar o aparelho. Confira a voltagem da sua tomada e a do produto.',
  ],
  'micro-ondas': [
    'De 20 a 25 L atende uma pessoa ou um casal; para família, 30 L ou mais. Prato grande exige mais espaço.',
    'Quanto maior, mais rápido aquece. Potência baixa demora e pode esquentar de forma desigual.',
    'Programas para pipoca e descongelar ajudam. Um painel simples evita erros.',
    'Ligar na tensão errada pode queimar o aparelho. Confira a voltagem da sua tomada e a do produto.',
    'Prato grande comporta travessas maiores. Confira se a sua marmita cabe e gira livremente.',
  ],
  'cadeiras-gamer': [
    'Confira o limite informado e escolha com margem. Modelos mais robustos tendem a durar mais.',
    'Quanto mais regulagens, mais fácil ajustar ao seu corpo. Braços ajustáveis ajudam a evitar dor nos ombros.',
    'Couro sintético esquenta; tecido respira melhor. Em longas horas, o conforto da espuma importa mais que o visual.',
    'O pistão é o que sustenta o peso. Procure pistão de classe 4 e relatos de durabilidade.',
    'Cadeira sofre desgaste. Garantia de pelo menos 1 ano, com peças de reposição, dá mais segurança.',
  ],
  'cadeiras-de-escritorio': [
    'A curva da lombar deve acompanhar a sua coluna. Ajuste de altura do encosto ajuda quem passa muitas horas sentado.',
    'Pés apoiados no chão e braços na altura da mesa evitam dor nos ombros e nos punhos.',
    'A tela respira melhor no calor; a espuma densa é confortável por horas, mas esquenta mais.',
    'Escolha com margem acima do seu peso. Isso afeta a durabilidade do pistão e da estrutura.',
    'Veja se vem com ferramentas e manual claros. Rodinhas e pistão costumam ser a parte mais difícil.',
  ],
  colchoes: [
    'Meça o quarto e a cama. Os tamanhos variam entre marcas: confira as medidas em centímetros.',
    'Densidade maior da espuma costuma indicar mais durabilidade. Molas ensacadas isolam melhor o movimento do parceiro.',
    'Quem dorme de lado costuma preferir mais macio; de barriga para cima ou com mais peso, mais firme.',
    'Colchão alto pede lençol com elástico fundo. Veja a altura e se cabe na sua cama.',
    'A garantia mostra o que o fabricante acredita sobre a durabilidade. Leia as condições (afundamento, uso correto).',
  ],
  'whey-protein': [
    'Compare os gramas de proteína por porção, não o peso do pote. Em geral, bons produtos trazem de 20 a 30 g por dose.',
    'O concentrado é o mais barato; o isolado tem menos lactose e gordura; o hidrolisado costuma ser vendido como de absorção mais rápida e custa mais.',
    'Divida o preço do pote pelo número de doses. Pote maior pode sair mais barato por dose.',
    'Sabor e dissolução variam bastante. Se puder, comece com um pote menor.',
    'Desconfie de pote sem informações claras. Prefira marcas que divulguem rótulo nutricional e laudos.',
  ],
  creatinas: [
    'É a forma mais estudada. Misturas com outros ingredientes podem encarecer sem vantagem comprovada.',
    'Procure marcas que divulguem laudo de pureza. Produto sem informação clara é um risco.',
    'A dose diária costuma ser de poucos gramas, então um pote dura semanas. Divida o preço pelas doses para comparar.',
    'Pote maior costuma sair mais barato por dose, se você vai usar todos os dias.',
    'Suplemento não é para todo mundo. Quem tem problema nos rins ou usa remédios deve consultar um médico antes.',
  ],
  'tenis-de-corrida': [
    'Pisada neutra, pronada ou supinada pede suporte diferente. Lojas especializadas costumam fazer a avaliação.',
    'Tênis mais leve cansa menos em provas; para treino diário, conforto e amortecimento pesam mais.',
    'Solado para asfalto é diferente do de trilha. Veja o desenho e o tipo de borracha.',
    'Malha respirável evita calor e bolhas. Veja se há reforço nos pontos de atrito.',
    'Deixe cerca de um dedo de folga na frente. O pé incha durante a corrida: prove no fim do dia.',
  ],
  'mouses-gamer': [
    'DPI alto não significa mouse melhor. O que importa é um sensor preciso e poder ajustar a sensibilidade.',
    'Mouse que não encaixa na mão cansa. Mãos grandes pedem modelos maiores; mãos pequenas, mais compactos.',
    'Com fio não depende de bateria e tem atraso mínimo. Sem fio de boa marca já é rápido o bastante para a maioria.',
    'Botões laterais ajudam em jogos de estratégia e MMO. Para tiro, poucos botões bem posicionados bastam.',
    'Os switches informam quantos milhões de cliques aguentam. Clique "duplo" em poucos meses é defeito comum em modelos baratos.',
  ],
  'teclados-mecanicos': [
    'O linear é suave e silencioso; o tátil dá um "toque" ao acionar; o clicky faz barulho e responde com som. Teste, se puder.',
    'O completo tem teclado numérico; o TKL economiza espaço; o 60% é compacto, mas sem setas e teclas de função.',
    'Com fio é estável e sem bateria. Sem fio dá liberdade, mas exige recarregar.',
    'RGB é estético. Se quiser programar teclas, veja se o software funciona no seu sistema.',
    'Teclados "hot-swap" permitem trocar os switches sem solda. Boa opção para personalizar depois.',
  ],
  'headsets-gamer': [
    'Almofadas macias e peso baixo fazem diferença. Evite pressão forte nas orelhas ou nos óculos.',
    'Cancelamento de ruído no microfone ajuda quem joga em equipe. Microfone removível é bom para uso fora do jogo.',
    'Confira a conexão (USB, P2 ou sem fio) e se funciona no seu console. "Surround 7.1" costuma ser simulado, não garante qualidade.',
    'Sem fio é prático, mas depende de bateria e de alcance. Com fio é mais estável e não precisa recarregar.',
    'Headset pesado cansa o pescoço em sessões longas. Veja o peso informado e o ajuste do arco.',
  ],
  'roteadores-wifi': [
    'O Wi-Fi 6 lida melhor com muitos aparelhos ao mesmo tempo, mas só ajuda se os seus dispositivos também forem compatíveis.',
    'A faixa de 2,4 GHz alcança mais longe; a de 5 GHz é mais rápida de perto. Banda dupla deixa você usar a melhor para cada aparelho.',
    'Em casa grande ou com muitas paredes, um roteador só pode não bastar. Sistemas mesh cobrem melhor.',
    'Quatro portas é o comum. Se você tem TV, PC e videogame no cabo, conte as portas antes de comprar.',
    'Um aplicativo simples facilita trocar a senha e ver quem está conectado. Veja se o app tem boas avaliações.',
  ],
  'power-banks': [
    'Um de 10.000 mAh carrega um celular comum cerca de 2 vezes na prática, por causa das perdas na conversão.',
    'Se o seu celular tem carga rápida, o power bank precisa suportar o mesmo padrão (como o PD) para carregar rápido.',
    'USB-C e USB-A dão flexibilidade. Duas saídas deixam carregar dois aparelhos ao mesmo tempo.',
    'Capacidade grande pesa. Para o dia a dia, 10.000 mAh costuma ser um bom equilíbrio.',
    'Procure proteções contra sobrecarga e curto-circuito e o selo da Anatel. Evite marcas desconhecidas.',
  ],
  tablets: [
    'Telas de 10 polegadas são boas para vídeo e leitura. Resolução baixa deixa o texto serrilhado.',
    '64 GB enche rápido com apps e vídeos. Se possível, escolha 128 GB, ou um modelo com cartão de memória.',
    'Veja as horas de vídeo informadas e relatos de uso. Tablet para viagem precisa de bateria que dure o dia.',
    'Nem todo tablet aceita caneta, e as canetas costumam ser vendidas à parte. Confira a compatibilidade.',
    'Tablet sem atualizações vira risco de segurança e perde apps. Veja a versão atual e a política do fabricante.',
  ],
  'cameras-de-seguranca': [
    'Full HD (1080p) já mostra bem. Resoluções maiores ajudam a reconhecer rostos de mais longe, mas ocupam mais armazenamento.',
    'Veja o alcance do infravermelho e se tem visão colorida à noite. Isso muda muito a imagem de madrugada.',
    'Cartão de memória não tem mensalidade, mas se a câmera for roubada, as gravações vão junto. A nuvem costuma ser paga.',
    'Permite ouvir e falar pelo celular. Útil para pets, crianças ou entregas, desde que a conexão seja boa.',
    'Câmera externa precisa de proteção contra água e poeira, como IP65 ou superior. Para uso interno, não é necessário.',
  ],
  furadeiras: [
    'A bateria é prática, mas a carga acaba e a bateria é cara de repor. Com fio rende o dia todo, com mais força.',
    'Torque é a força do giro. Para parede e concreto, busque mais potência; para madeira e parafuso, menos já basta.',
    'Um mandril de 13 mm aceita brocas maiores. Duas velocidades ajudam a furar e a parafusar com mais controle.',
    'O impacto é necessário para concreto e alvenaria. Sem ele, só madeira, metal e parafusos.',
    'A maleta protege e organiza. Veja se vêm brocas e bits, ou se será preciso comprar à parte.',
  ],
  'panelas-eletricas': [
    'De 3 a 5 L atende de 1 a 4 pessoas. Capacidade maior do que a necessária gasta mais energia e espaço.',
    'Timer e funções prontas (arroz, sopa, mexido) tiram o trabalho de vigiar. Veja se ela mantém aquecido depois.',
    'Antiaderente de boa qualidade evita grudar, mas risca com talher de metal. Use utensílios de silicone ou madeira.',
    'Maior potência cozinha mais rápido, mas gasta mais. Compare com a capacidade.',
    'Panela interna removível facilita. Tampa com muitas peças dá mais trabalho.',
  ],
  'secadores-de-cabelo': [
    'Em geral, 2000 W ou mais seca mais rápido. Várias temperaturas ajudam a proteger o cabelo do calor.',
    'Secador pesado cansa o braço em cabelo comprido. Veja o peso e como a empunhadura encaixa na mão.',
    'A função íon costuma reduzir o frizz e o tempo de secagem em alguns cabelos. Não é milagre, mas pode ajudar.',
    'Cabo curto limita o uso. Pelo menos 1,8 m dá liberdade; cabo giratório evita embolar.',
    'Difusor ajuda em cabelo cacheado; concentrador dá precisão na escova. Veja o que vem na caixa.',
  ],
  'barbeadores-eletricos': [
    'Modelo que aceita água permite barbear no banho e é mais fácil de lavar. Pele sensível costuma gostar de espuma.',
    'Veja quantos minutos de uso por carga e se funciona enquanto carrega. Para viagem, importa também o tempo de recarga.',
    'A lâmina foil costuma dar acabamento mais rente em barba curta; a rotativa costuma acompanhar melhor o contorno do rosto.',
    'Cabeça removível que pode ser lavada em água corrente deixa a limpeza rápida e mais higiênica.',
    'Aparador de barba e pentes de tamanhos diferentes aumentam o uso. Confira o que acompanha.',
  ],
  'consoles-de-video-game': [
    'Cada console tem os seus exclusivos. Veja se os jogos que você quer existem na plataforma antes de comprar.',
    'Sem leitor de disco é mais barato, mas só roda jogos digitais, geralmente mais caros e sem revenda.',
    'Os jogos de hoje ocupam dezenas de GB e o armazenamento enche rápido. Veja se aceita expansão.',
    'Em alguns consoles, jogar online exige assinatura paga. Some esse custo ao comparar.',
    'Kits com jogos ou segundo controle podem compensar. Compare o preço de cada item separado.',
  ],
};

/** A explicação do critério de posição `i` do tipo, se houver. */
export function explicacaoDoCriterio(slug: string, i: number): string | undefined {
  return EXPLICACOES_DOS_CRITERIOS[slug]?.[i];
}
